### ISSUE TITLE
MacOS build of Dopamine is borked due to better-sqlite

### ISSUE THREAD

**Issue by g-yui** [digimezzo/dopamine#157]
Frankly I know nothing of MacOS, I just ran the install script on it and it got borked due to a fail "at the better-sqlite3@7.1.1 build-release script."
This was built using "macos-latest", here's the whole build and the resulting dump if you want to check it out: [MacOS build status](https://github.com/g-yui/dopamine/runs/3375677706?check_suite_focus=true).

Good thing is, I managed to get the other builds working, I'll clean up the yml code and add support for uploading the artifacts so #149 can be finally put to rest o((>ω< ))o

Keep up the good work 👍

**Comment by digimezzo** [comment]
@g-yui I seem to have fixed the better-sqlite build issue by upgrading better-sqlite3. I now have a missing icons error (due to file associations which are configured in electron-builder.json) :). I must now create some mac icons, in .icns format, for the supported file types). That'll probably be for tomorrow.

**Comment by digimezzo** [comment]
@g-yui The mac build is now fixed.

**Comment by g-yui** [comment]
Nice, thanks :D

**Comment by digimezzo** [comment]
Now we need someone with a mac to test it out. I have no idea if it runs :)

**Comment by g-yui** [comment]
Neither do I! But it does compile, so I'd call that a win :D
