### ISSUE TITLE
Equilizer 

### ISSUE THREAD

**Issue by Arnab11** [digimezzo/dopamine#199]
Where is the equilizer in dopamine 3? it's been really handy in dopamine 2. Please add this.

One more request please make linux packages as Snap/Flatpak

**Comment by Muspellheimer** [comment]
its pre release and in full dev mode.

use your brain... thank you

**Comment by digimezzo** [comment]
@Arnab11 Sorry for my late reply and sorry for the extremely rude response that you got from @Muspellheimer. This is not the kind of attitude that I want on this repository.

Dopamine 3 is currently in preview mode. It was built from scratch to provide cross-platform support. That is a big task which takes a longtime and because of that, Dopamine 3 is still missing a lot of features compared to Dopamine 2. But we'll get there eventually.

**Comment by Arnab11** [comment]
> @Arnab11 Sorry for my late reply and sorry for the extremely rude response that you got from @Muspellheimer. This is not the kind of attitude that I want on this repository.
> 
> Dopamine 3 is currently in preview mode. It was built from scratch to provide cross-platform support. That is a big task which takes a longtime and because of that, Dopamine 3 is still missing a lot of features compared to Dopamine 2. But we'll get there eventually.

Thanks for the reply, I am really excited for the dopamine 3 release. Also it will run on linux. also love the interface of dopamine 3, Thanks for the hard work.

**Comment by Muspellheimer** [comment]
ok you little fuck up it seems like you are confused...

rude and reallity isnt the same thing... keep sucking dick you little fuck shit...

**Comment by digimezzo** [comment]
@Arnab11 You're very welcome :) Thank you for loving Dopamine.
