### ISSUE TITLE
What I need to change dopamine

### ISSUE THREAD

**Issue by grafmariyan** [digimezzo/dopamine#201]
So I want to add playlist option but I have no idea what I need for that. I already know some html css is that enough?

**Comment by digimezzo** [comment]
@grafmariyan Thanks for willing to help. I'm afraid that some html and css knowlegde won't be enough. There's quite a big architecture in Typescript required to get this to work.
I'm currently already working on the playlist option. It's taking some time, because life is rather busy right now, but I'm working on it everyday. I'm trying to get it ready ASAP.

**Comment by grafmariyan** [comment]
Yo do very good job. People should donate more to devs like you

На сб, 20 ное 2021 г., 14:08 Digimezzo ***@***.***> написа:

**Comment by digimezzo** [comment]
@grafmariyan Thank you!

**Comment by Parzival5129** [comment]
@digimezzo Glad to hear you are still on it. So many music programs have been cancelled already. Take your time. Im very excited for the new playlist feature you are working on. Its one of the most important features directly after the ability to edit songs!

**Comment by AKmatiAK** [comment]
I'll donate next month when I get salary to keep this great project alive ;)

**Comment by digimezzo** [comment]
Playlist support was added in Preview 8. It'll still get improvements over the next previews.
