### ISSUE TITLE
Dopamine crashes on custom themes which have unsupported properties

### ISSUE THREAD

**Issue by Ahmed-Ali7** [digimezzo/dopamine#208]
can't start , I got error then it closes
windows 10

**Comment by digimezzo** [comment]
Could you send the log file?

**Comment by Ahmed-Ali7** [comment]
> 
[Dopamine.log](https://github.com/digimezzo/dopamine/files/7796846/Dopamine.log)

**Comment by digimezzo** [comment]
The crash is caused by a custom theme that is not supported anymore in Preview 7. You'll have to remove the custom theme so Dopamine uses the default theme at the next startup. Then you can re-create your custom theme using the the new theme structure. Such situations are handled badly in preview 7. I'll make this more user friendly in preview 8.

**Comment by Ahmed-Ali7** [comment]
> 

done. thanks. it's working normally now.

**Comment by digimezzo** [comment]
@Ahmed-Ali7 You're welcome. I've reopened the issue and modified the title a bit, so I remember to fix it for preview 8. Thanks for reporting this problem.
