### ISSUE TITLE
Crash on launch in Linux

### ISSUE THREAD

**Issue by roozbehzarei** [digimezzo/dopamine#273]
Dopamine crashes on launch in Linux. Here's the associated log:

> [2022-08-08 23:43:51.958] [info]  [Main] [] +++ Starting +++
> [2022-08-08 23:43:51.963] [info]  [Main] [] Attempt to run second instance. Showing existing window.
> [2022-08-08 23:43:51.965] [info]  [Main] [] There is already another instance running. Closing.

Dopamine: v3.0.0-preview12
Linux: Ubuntu-based 22.04 LTS

**Comment by digimezzo** [comment]
Note to self: could this be caused by the build environment. Maybe the Linux build is done on a non-LTS version of Ubuntu?

**Comment by digimezzo** [comment]
I've tested this out and with Preview 11 and 12 Dopamine indeed crashes on Ubuntu. I've since updated a lot of components and the latest builds don't crash anymore. I suspect the crash was caused by an out of date Electron version. However, it is not 100% clear. So, preview 13 should fix this issue.
