### ISSUE TITLE
Few suggestions + 1 issue

### ISSUE THREAD

**Issue by DreamPhreak** [digimezzo/dopamine#277]
I am loving this program so far, but I want to give a few suggestions:

1) Left-clicking on the tray icon doesn't open the program. Have to right-click, and then left click the option that appears. Would be nice to make it a single left click to open it.

2) One thing I look for in a music player is a rating system because the rating system built into windows is awful. I know this would probably be a lot of work to implement, but I just wanted to say it.

3) ~~Not a suggestion, but an issue: I made a new playlist, and I wanted to add a song to it, but when I right-click on the song, then go to "Add to playlist", the playlist I made isnt there. I restarted the program but it still doesnt appear, only says "No playlists".~~  Nvm, I figured this out. It turns out I made a "playlist FOLDER" and not an actual "playlist".

**Comment by MadMarco64** [comment]
I've been having the same issue, but i dont know how to make the actual playlist myself..

**Comment by digimezzo** [comment]
@MadMarco64 Could you show me a screenshot of your Playlists screen?

**Comment by digimezzo** [comment]
I broke the playlists screen in Preview 15 it seems. I've fixed the problem. It will be released in Preview 16 (release tomorrow).

**Comment by digimezzo** [comment]
Fixed in f46192f811891bef813f253b744322fa20fd2cb3

**Comment by digimezzo** [comment]
@DreamPhreak Sorry for hijacking your issue for the playlist screen issue :) To answer you questions:

1. Issue #297 explains why this, unfortunately, isn't possible.
2. Rating has, since you logged the issue, been implemented.
3. Preview 16 (release tomorrow) will add small improvements to the playlist screen to make it clear when a playlist folder does not have playlists yet.
