### ISSUE TITLE
Releases with the same name by the same artist are grouped as one

### ISSUE THREAD

**Issue by mariqtereza** [digimezzo/dopamine#354]
I've noticed this when trying to organize my Bullet for My Valentine discography.
They have 2 releases with the same name and Dopamine groups them as one release.
Is there a workaround for this ? 

![image_2022-11-21_231215663](https://user-images.githubusercontent.com/118773870/203159131-cb29dd63-c155-4006-9e7c-47788028d341.png)

**Comment by digimezzo** [comment]
The album title needs to be different. Dopamine uses the combination of album title and album artist tag to group tracks into albums. Do other players creat differently with those tracks.

**Comment by MulverineX** [comment]
You could add a heuristic to fix this via album art hash maybe? But yeah Dopamine uses local data, it doesn't itemize tracks on a hosted metadata DB, so unless there's different album art there's no way to fix this (without you manually adding (2) to the album title.

**Comment by mariqtereza** [comment]
Is what MulverineX said possible ? Using the album art as heuristic to fix this ?
Thank you for the answer !

**Comment by digimezzo** [comment]
I'm not sure I want to do this. I've seen strange collections where a single album has different pictures for its different songs. It would complicate things a lot.

**Comment by Niavlys77** [comment]
What about making use of album's directory paths for the grouping logic? Assuming the user has all their albums placed in their own distinct folders.. which I imagine some people might not do this.

I think this might be the best solution despite that, as it'd give users a method of resolving the mistaken grouping on their own accord (while also forcing those who care enough to better organize their music).

**Comment by curbia** [comment]
Releases by the same name are grouped together even if by different artists. Dopamine seems to use the art for the release from whichever artist comes first alphabetically.

**Comment by digimezzo** [comment]
@curbia Could you show an example? Dopamine groups tracks that have the same "album artist" and "track title". There is no other logic in there. is the album artist for these tracks empty or do they have the same album artist (for example "Various artists").

**Comment by curbia** [comment]
![image](https://user-images.githubusercontent.com/87792521/225914221-1ac6f3c9-1b71-4284-b8e0-f50292fc4e91.png)

Here I'm on an artist page. It's showing the cover for another album by the same name (Iconoclast) instead of the one for this artist's album. Then in the sidebar with the track listings, it shows both artists' tracks. Tag info below.

![image](https://user-images.githubusercontent.com/87792521/225914970-60e9c348-73c7-44c8-9cfd-22ebf3024790.png)
![image](https://user-images.githubusercontent.com/87792521/225915061-99daed1f-3199-414b-b610-2c5f1fa32fbb.png)

**Comment by mariqtereza** [comment]
![image_2023-03-22_182712311](https://user-images.githubusercontent.com/118773870/226972328-3747e510-33d6-4f1b-b8da-925f8c8d5629.png)

Thank you for the comments and the responsiveness !
Here you can see another example.
Ovid's Withering have an EP from 2014 called Terraphage and an album from 2020 with the same name.
I group releases in the same artist with the "Album artists" tag, but when an artist/band has 2 releases with the same name, they get grouped into one release.
Here I have labeled the EP as Disc 2, so I can at least have a visual seperation.
Is there a way to have release by the same album artist with the same name to be grouped seperately ?

**Comment by yurisuika** [comment]
In MusicBee you can determine what counts as an album by what folder the files are in, or by your own configuration of tag fields. For many years that was my software of choice largely for that functionality. I have so many albums titled "Demo" from the same year, or multiple releases by an artist of the same name, sometimes even within the same year (so I end up having to break from convention in my folder naming strategy there... usually it works out that the solution is to append "EP" to the album name).

As mentioned previously, determining by folder is probably the best solution for this issue.

On another note, it seems Dopamine will split albums by file type. Sometimes I end up having a mix of MP3 and FLAC because a lot of my library comes from vinyl/cassette rips which only ever existed in those formats and for some reason archivists only ever have one side of a split for whatever reason, so Dopamine ends up splitting those into multiple albums.

So two ends of the same stick here, splitting functionality not present and desired, and splitting functionality present and not desired.

**Comment by digimezzo** [comment]
@Note to self, this is how MusicBee does it:

![image](https://github.com/digimezzo/dopamine/assets/11945339/68752637-3e13-4b33-bde2-e3df29a0b9d4)
