### ISSUE TITLE
Latest Version Suggestions

### ISSUE THREAD

**Issue by DopamineUser** [digimezzo/dopamine#535]
- The visualizer's middle line isn't aligned with the pause button, should be moved slightly to the left.
![image](https://github.com/digimezzo/dopamine/assets/148219987/b781c8a7-c913-4065-8f2e-f7a11f94e43e)

- Would be great if the visualizer size (width and detail/amount of lines) could be adjusted, as right now it's a bit too small and low detailed.

- I would prefer if the tray didn't fade out on the now playing screen, because I like being able to see which part of the track I am at without having to move the mouse over the dopamine window every time.

- I haven't seen any differences from having the check for updates & pre-releases options on, is it not programmed yet? I imagined it would notify when a new release is available.

**Comment by digimezzo** [comment]
Thanks for reporting these problems:

- Created issue #535 for the visualizer.
- Created issue #537 for playback controls visibility on now playing screens

The update check was a mistake on my side when labeling the preview 22 release in GitHub. Due to the mistake, the update checker wasn't able to determine if preview 22 was newer than 21. I've now fixed the labeling and the update checker will now report that an update is available.
